### ISSUE TITLE
Data quality issues not appearing on tasklist page

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#597] opened 2024-10-29 11:49 UTC
## Context:

- Data quality issues aren't being displayed on [Plymouth's task list page](https://submit.planning.data.gov.uk/organisations/local-authority:PLY/brownfield-land).
- They have two data quality issues that should be appearing on this page.
- Expected behaviour: the LPA should be able to see a task list of all data quality issues that require their attention (i.e. showing all data quality issues but excluding issues that are of severity type 'warning' or 'notice').

**Comment by GeorgeGoodall-GovUk** [comment] 2024-10-31 10:11
archiving this as its a duplicate of #600

**Closed by GeorgeGoodall-GovUk** 2024-10-31 10:11 UTC
Labels: bug
